services:
  gpe-phantom:
    networks:
      - default
      - gpe_net
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpe-phantom
    restart: unless-stopped
    ports:
      - "8317:8317"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
    # ПРИНУДИТЕЛЬНЫЙ ЗАПУСК С КОНФИГОМ
    command: ["/CLIProxyAPI/CLIProxyAPIPlus", "--config", "/CLIProxyAPI/config.yaml"]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: gphantom-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
networks:
  gpe_net:
    external: true
